name: End-to-end tests
on:
  # schedule:
  #   - cron: '0 */12 * * *'
  pull_request:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Cypress run
        uses: cypress-io/github-action@v5
