name: End-to-end tests
on:
  schedule:
    - cron: '0 */12 * * *'
  pull_request:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Cypress run
        uses: cypress-io/github-action@v5
