name: DevSkim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.1
    - name: Run DevSkim
      uses: microsoft/DevSkim-Action@v1
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: devskim-results.sarif
