name: DevSkim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Run DevSkim
      uses: microsoft/DevSkim-Action@v1
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: devskim-results.sarif
