name: DevSkim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Run DevSkim
      uses: microsoft/DevSkim-Action@v1
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: devskim-results.sarif
