name: DevSkim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Run DevSkim
      uses: microsoft/DevSkim-Action@v1
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: devskim-results.sarif
